version: 2.1

jobs:
  build:
    docker:
      - image: node:16.13-browsers-legacy
    steps:
      - checkout
      - run:
          name: Install packages
          command: npm ci
      - run:
          name: Build project
          command: npm run build
  deploy:
    docker:
      - image: node:16.13-browsers-legacy
    steps:
      - checkout
      - run:
          name: Install packages
          command: npm ci
      - run:
          name: Build project
          command: npm run build
      - run:
          name: Installing Firebase-Tools
          command: npm run firebase-tools
      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
          
workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

