version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.15-browsers
    steps:
      - checkout
      - run:
          name: Install packages
          command: npm ci
      - run:
          name: Build project
          command: npm run build
  deploy:
    docker:
      - image: cimg/node:16.15-browsers
    steps:
      - checkout
      - run:
          name: Install packages
          command: npm ci
      - run:
          name: Build project
          command: npm run build
      - run:
          name: Firebase Deploy
          command: npm install firebase-tools && firebase deploy --token "$FIREBASE_TOKEN"
          
workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

